# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: vanus.linkall.com/v1alpha1
kind: Controller
metadata:
  name: vanus-controller
  namespace: vanus
spec:
  # replicas is the number of controllers.
  replicas: 3
  # controllerImage is the customized docker image repo of the RocketMQ Controller
  image: public.ecr.aws/vanus/controller:v0.5.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

---
apiVersion: vanus.linkall.com/v1alpha1
kind: Store
metadata:
  name: vanus-store
  namespace: vanus
spec:
  # replicas is the number of stores.
  replicas: 3
  # storeImage is the customized docker image repo of the RocketMQ Controller
  image: public.ecr.aws/vanus/store:v0.5.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

---
apiVersion: vanus.linkall.com/v1alpha1
kind: Trigger
metadata:
  name: vanus-trigger
  namespace: vanus
spec:
  # triggerImage is the customized docker image repo of the RocketMQ Controller
  image: public.ecr.aws/vanus/trigger:v0.5.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent

---
apiVersion: vanus.linkall.com/v1alpha1
kind: Timer
metadata:
  name: vanus-timer
  namespace: vanus
spec:
  # timerImage is the customized docker image repo of the RocketMQ Controller
  image: public.ecr.aws/vanus/timer:v0.5.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent

---
apiVersion: vanus.linkall.com/v1alpha1
kind: Gateway
metadata:
  name: vanus-gateway
  namespace: vanus
spec:
  # gatewayImage is the customized docker image repo of the Vanus Controller
  image: public.ecr.aws/vanus/gateway:v0.5.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent