// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateClusterOKCode is the HTTP code returned for type CreateClusterOK
const CreateClusterOKCode int = 200

/*
CreateClusterOK OK

swagger:response createClusterOK
*/
type CreateClusterOK struct {

	/*
	  In: Body
	*/
	Payload *CreateClusterOKBody `json:"body,omitempty"`
}

// NewCreateClusterOK creates CreateClusterOK with default headers values
func NewCreateClusterOK() *CreateClusterOK {

	return &CreateClusterOK{}
}

// WithPayload adds the payload to the create cluster o k response
func (o *CreateClusterOK) WithPayload(payload *CreateClusterOKBody) *CreateClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cluster o k response
func (o *CreateClusterOK) SetPayload(payload *CreateClusterOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
