// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/linkall-labs/vanus-operator/api/models"
)

// CreateClusterHandlerFunc turns a function with the right signature into a create cluster handler
type CreateClusterHandlerFunc func(CreateClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateClusterHandlerFunc) Handle(params CreateClusterParams) middleware.Responder {
	return fn(params)
}

// CreateClusterHandler interface for that can handle valid create cluster params
type CreateClusterHandler interface {
	Handle(CreateClusterParams) middleware.Responder
}

// NewCreateCluster creates a new http.Handler for the create cluster operation
func NewCreateCluster(ctx *middleware.Context, handler CreateClusterHandler) *CreateCluster {
	return &CreateCluster{Context: ctx, Handler: handler}
}

/* CreateCluster swagger:route POST /cluster/ cluster createCluster

创建一个 Cluster

*/
type CreateCluster struct {
	Context *middleware.Context
	Handler CreateClusterHandler
}

func (o *CreateCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateClusterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateClusterOKBody create cluster o k body
//
// swagger:model CreateClusterOKBody
type CreateClusterOKBody struct {

	// code
	// Required: true
	Code *int32 `json:"code"`

	// data
	// Required: true
	Data *models.ClusterInfo `json:"data"`

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create cluster o k body
func (o *CreateClusterOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateClusterOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("createClusterOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *CreateClusterOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("createClusterOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createClusterOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *CreateClusterOKBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createClusterOK"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create cluster o k body based on the context it is used
func (o *CreateClusterOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateClusterOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createClusterOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateClusterOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateClusterOKBody) UnmarshalBinary(b []byte) error {
	var res CreateClusterOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
