// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteClusterOKCode is the HTTP code returned for type DeleteClusterOK
const DeleteClusterOKCode int = 200

/*DeleteClusterOK OK

swagger:response deleteClusterOK
*/
type DeleteClusterOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteClusterOKBody `json:"body,omitempty"`
}

// NewDeleteClusterOK creates DeleteClusterOK with default headers values
func NewDeleteClusterOK() *DeleteClusterOK {

	return &DeleteClusterOK{}
}

// WithPayload adds the payload to the delete cluster o k response
func (o *DeleteClusterOK) WithPayload(payload *DeleteClusterOKBody) *DeleteClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster o k response
func (o *DeleteClusterOK) SetPayload(payload *DeleteClusterOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
