// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/linkall-labs/vanus-operator/api/models"
)

// DeleteClusterHandlerFunc turns a function with the right signature into a delete cluster handler
type DeleteClusterHandlerFunc func(DeleteClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteClusterHandlerFunc) Handle(params DeleteClusterParams) middleware.Responder {
	return fn(params)
}

// DeleteClusterHandler interface for that can handle valid delete cluster params
type DeleteClusterHandler interface {
	Handle(DeleteClusterParams) middleware.Responder
}

// NewDeleteCluster creates a new http.Handler for the delete cluster operation
func NewDeleteCluster(ctx *middleware.Context, handler DeleteClusterHandler) *DeleteCluster {
	return &DeleteCluster{Context: ctx, Handler: handler}
}

/* DeleteCluster swagger:route DELETE /cluster/ cluster deleteCluster

delete Cluster

*/
type DeleteCluster struct {
	Context *middleware.Context
	Handler DeleteClusterHandler
}

func (o *DeleteCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteClusterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteClusterOKBody delete cluster o k body
//
// swagger:model DeleteClusterOKBody
type DeleteClusterOKBody struct {

	// code
	// Required: true
	Code *int32 `json:"code"`

	// data
	// Required: true
	Data *models.ClusterInfo `json:"data"`

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete cluster o k body
func (o *DeleteClusterOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteClusterOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("deleteClusterOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *DeleteClusterOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("deleteClusterOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteClusterOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *DeleteClusterOKBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteClusterOK"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this delete cluster o k body based on the context it is used
func (o *DeleteClusterOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteClusterOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteClusterOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteClusterOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteClusterOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteClusterOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
