// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterParams creates a new GetClusterParams object
//
// There are no default values defined in the spec.
func NewGetClusterParams() GetClusterParams {

	return GetClusterParams{}
}

// GetClusterParams contains all the bound params for the get cluster operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCluster
type GetClusterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*true 显示 cluster 详细信息
	  In: query
	*/
	Detail *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClusterParams() beforehand.
func (o *GetClusterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDetail, qhkDetail, _ := qs.GetOK("detail")
	if err := o.bindDetail(qDetail, qhkDetail, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDetail binds and validates parameter Detail from query.
func (o *GetClusterParams) bindDetail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Detail = &raw

	return nil
}
