// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/vanus-labs/vanus-operator/api/models"
)

// NewPatchClusterParams creates a new PatchClusterParams object
//
// There are no default values defined in the spec.
func NewPatchClusterParams() PatchClusterParams {

	return PatchClusterParams{}
}

// PatchClusterParams contains all the bound params for the patch cluster operation
// typically these are obtained from a http.Request
//
// swagger:parameters patchCluster
type PatchClusterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*patch info
	  Required: true
	  In: body
	*/
	Patch *models.ClusterPatch
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchClusterParams() beforehand.
func (o *PatchClusterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ClusterPatch
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("patch", "body", ""))
			} else {
				res = append(res, errors.NewParseError("patch", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Patch = &body
			}
		}
	} else {
		res = append(res, errors.Required("patch", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
