// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchClusterOKCode is the HTTP code returned for type PatchClusterOK
const PatchClusterOKCode int = 200

/*PatchClusterOK OK

swagger:response patchClusterOK
*/
type PatchClusterOK struct {

	/*
	  In: Body
	*/
	Payload *PatchClusterOKBody `json:"body,omitempty"`
}

// NewPatchClusterOK creates PatchClusterOK with default headers values
func NewPatchClusterOK() *PatchClusterOK {

	return &PatchClusterOK{}
}

// WithPayload adds the payload to the patch cluster o k response
func (o *PatchClusterOK) WithPayload(payload *PatchClusterOKBody) *PatchClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch cluster o k response
func (o *PatchClusterOK) SetPayload(payload *PatchClusterOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
