// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Vanus Operator Interface Document
//
//  this document describes the functions, parameters and return values of the vanus operator API
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1/vanus
//  Version: v0.2.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
