// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "this document describes the functions, parameters and return values of the vanus operator API\n",
    "title": "Vanus Operator Interface Document",
    "version": "v0.2.0"
  },
  "basePath": "/api/v1/vanus",
  "paths": {
    "/cluster/": {
      "get": {
        "description": "获取一个 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "getCluster",
        "parameters": [
          {
            "type": "string",
            "description": "true 显示 cluster 详细信息",
            "name": "detail",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "创建一个 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "createCluster",
        "parameters": [
          {
            "description": "需要创建的Cluster信息",
            "name": "cluster",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "删除 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "deleteCluster",
        "parameters": [
          {
            "type": "string",
            "description": "true 表示强制删除，默认为false",
            "name": "force",
            "in": "query"
          },
          {
            "description": "需要删除的 Cluster",
            "name": "cluster",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "集群手动伸缩",
        "tags": [
          "cluster"
        ],
        "operationId": "patchCluster",
        "parameters": [
          {
            "description": "伸缩信息",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connector/": {
      "get": {
        "description": "获取一个 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "getConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "创建一个 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "createConnector",
        "parameters": [
          {
            "description": "需要创建的Connector信息",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "删除 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "deleteConnector",
        "parameters": [
          {
            "type": "string",
            "description": "true 表示强制删除，默认为false",
            "name": "force",
            "in": "query"
          },
          {
            "description": "需要删除的 Connector",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/": {
      "get": {
        "description": "Connector 列表",
        "tags": [
          "connector"
        ],
        "operationId": "listConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "$ref": "#/definitions/Connector_info"
                  }
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Cluster_info": {
      "description": "集群信息",
      "type": "object",
      "properties": {
        "cloudevents_endpoints": {
          "description": "cloudevents端点",
          "type": "string"
        },
        "gateway_endpoints": {
          "description": "gateway端点",
          "type": "string"
        }
      }
    },
    "Cluster_patch": {
      "type": "object",
      "properties": {
        "version": {
          "description": "待更新的版本",
          "type": "string"
        }
      }
    },
    "Connector_info": {
      "description": "Connector 信息",
      "type": "object",
      "properties": {
        "kind": {
          "description": "connector 类型",
          "type": "string"
        },
        "name": {
          "description": "connector 名称",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "this document describes the functions, parameters and return values of the vanus operator API\n",
    "title": "Vanus Operator Interface Document",
    "version": "v0.2.0"
  },
  "basePath": "/api/v1/vanus",
  "paths": {
    "/cluster/": {
      "get": {
        "description": "获取一个 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "getCluster",
        "parameters": [
          {
            "type": "string",
            "description": "true 显示 cluster 详细信息",
            "name": "detail",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "创建一个 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "createCluster",
        "parameters": [
          {
            "description": "需要创建的Cluster信息",
            "name": "cluster",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "删除 Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "deleteCluster",
        "parameters": [
          {
            "type": "string",
            "description": "true 表示强制删除，默认为false",
            "name": "force",
            "in": "query"
          },
          {
            "description": "需要删除的 Cluster",
            "name": "cluster",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "集群手动伸缩",
        "tags": [
          "cluster"
        ],
        "operationId": "patchCluster",
        "parameters": [
          {
            "description": "伸缩信息",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connector/": {
      "get": {
        "description": "获取一个 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "getConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "创建一个 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "createConnector",
        "parameters": [
          {
            "description": "需要创建的Connector信息",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "删除 Connector",
        "tags": [
          "connector"
        ],
        "operationId": "deleteConnector",
        "parameters": [
          {
            "type": "string",
            "description": "true 表示强制删除，默认为false",
            "name": "force",
            "in": "query"
          },
          {
            "description": "需要删除的 Connector",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_info"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/": {
      "get": {
        "description": "Connector 列表",
        "tags": [
          "connector"
        ],
        "operationId": "listConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "$ref": "#/definitions/Connector_info"
                  }
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Cluster_info": {
      "description": "集群信息",
      "type": "object",
      "properties": {
        "cloudevents_endpoints": {
          "description": "cloudevents端点",
          "type": "string"
        },
        "gateway_endpoints": {
          "description": "gateway端点",
          "type": "string"
        }
      }
    },
    "Cluster_patch": {
      "type": "object",
      "properties": {
        "version": {
          "description": "待更新的版本",
          "type": "string"
        }
      }
    },
    "Connector_info": {
      "description": "Connector 信息",
      "type": "object",
      "properties": {
        "kind": {
          "description": "connector 类型",
          "type": "string"
        },
        "name": {
          "description": "connector 名称",
          "type": "string"
        }
      }
    }
  }
}`))
}
