// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "this document describes the functions, parameters and return values of the vanus operator API\n",
    "title": "Vanus Operator Interface Document",
    "version": "v0.2.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/cluster/": {
      "get": {
        "description": "get Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "getCluster",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "create Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "createCluster",
        "parameters": [
          {
            "name": "create",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_create"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "delete Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "deleteCluster",
        "parameters": [
          {
            "description": "delete Cluster",
            "name": "delete",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_delete"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "patchCluster",
        "parameters": [
          {
            "description": "patch info",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/": {
      "get": {
        "description": "list Connector",
        "tags": [
          "connector"
        ],
        "operationId": "listConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "$ref": "#/definitions/Connector_info"
                  }
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "create Connector",
        "tags": [
          "connector"
        ],
        "operationId": "createConnector",
        "parameters": [
          {
            "description": "Connector info",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_create"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Connectors",
        "tags": [
          "connector"
        ],
        "operationId": "patchConnectors",
        "parameters": [
          {
            "description": "patch info",
            "name": "connectors",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "$ref": "#/definitions/Connector_patch"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/ListOkErr"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/{name}": {
      "get": {
        "description": "get Connector",
        "tags": [
          "connector"
        ],
        "operationId": "getConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "delete Connector",
        "tags": [
          "connector"
        ],
        "operationId": "deleteConnector",
        "parameters": [
          {
            "type": "string",
            "description": "connector name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Connector",
        "tags": [
          "connector"
        ],
        "operationId": "patchConnector",
        "parameters": [
          {
            "description": "Connector info",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "connector name",
          "name": "name",
          "in": "path",
          "required": true
        }
      ]
    },
    "/healthz/": {
      "get": {
        "description": "healthz",
        "tags": [
          "healthz"
        ],
        "operationId": "healthz",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Health_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Cluster_create": {
      "description": "cluster create params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Cluster_delete": {
      "description": "cluster create params",
      "type": "object",
      "properties": {
        "force": {
          "description": "true means force delete, default false",
          "type": "boolean",
          "default": false
        }
      }
    },
    "Cluster_info": {
      "description": "cluster info",
      "type": "object",
      "properties": {
        "status": {
          "description": "cluster status",
          "type": "string"
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Cluster_patch": {
      "description": "cluster patch params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Connector_create": {
      "description": "Connector create params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "kind": {
          "description": "connector kind",
          "type": "string"
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "type": {
          "description": "connector type",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Connector_info": {
      "description": "Connector info",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "kind": {
          "description": "connector kind",
          "type": "string"
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "reason": {
          "description": "connector status reason",
          "type": "string"
        },
        "status": {
          "description": "connector status",
          "type": "string"
        },
        "type": {
          "description": "connector type",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Connector_patch": {
      "description": "Connector patch params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Health_info": {
      "description": "operator info",
      "type": "object",
      "properties": {
        "status": {
          "description": "operator status",
          "type": "string"
        }
      }
    },
    "ListOkErr": {
      "type": "object",
      "properties": {
        "failed": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "reason": {
                "type": "string"
              }
            }
          }
        },
        "successed": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "this document describes the functions, parameters and return values of the vanus operator API\n",
    "title": "Vanus Operator Interface Document",
    "version": "v0.2.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/cluster/": {
      "get": {
        "description": "get Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "getCluster",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "create Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "createCluster",
        "parameters": [
          {
            "name": "create",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_create"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "delete Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "deleteCluster",
        "parameters": [
          {
            "description": "delete Cluster",
            "name": "delete",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_delete"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Cluster",
        "tags": [
          "cluster"
        ],
        "operationId": "patchCluster",
        "parameters": [
          {
            "description": "patch info",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cluster_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Cluster_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/": {
      "get": {
        "description": "list Connector",
        "tags": [
          "connector"
        ],
        "operationId": "listConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "$ref": "#/definitions/Connector_info"
                  }
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "create Connector",
        "tags": [
          "connector"
        ],
        "operationId": "createConnector",
        "parameters": [
          {
            "description": "Connector info",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_create"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Connectors",
        "tags": [
          "connector"
        ],
        "operationId": "patchConnectors",
        "parameters": [
          {
            "description": "patch info",
            "name": "connectors",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "$ref": "#/definitions/Connector_patch"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/ListOkErr"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    },
    "/connectors/{name}": {
      "get": {
        "description": "get Connector",
        "tags": [
          "connector"
        ],
        "operationId": "getConnector",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "delete Connector",
        "tags": [
          "connector"
        ],
        "operationId": "deleteConnector",
        "parameters": [
          {
            "type": "string",
            "description": "connector name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "patch Connector",
        "tags": [
          "connector"
        ],
        "operationId": "patchConnector",
        "parameters": [
          {
            "description": "Connector info",
            "name": "connector",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Connector_patch"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Connector_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "connector name",
          "name": "name",
          "in": "path",
          "required": true
        }
      ]
    },
    "/healthz/": {
      "get": {
        "description": "healthz",
        "tags": [
          "healthz"
        ],
        "operationId": "healthz",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "code",
                "data",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int32",
                  "default": 200
                },
                "data": {
                  "type": "object",
                  "$ref": "#/definitions/Health_info"
                },
                "message": {
                  "type": "string",
                  "default": "success"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Cluster_create": {
      "description": "cluster create params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Cluster_delete": {
      "description": "cluster create params",
      "type": "object",
      "properties": {
        "force": {
          "description": "true means force delete, default false",
          "type": "boolean",
          "default": false
        }
      }
    },
    "Cluster_info": {
      "description": "cluster info",
      "type": "object",
      "properties": {
        "status": {
          "description": "cluster status",
          "type": "string"
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Cluster_patch": {
      "description": "cluster patch params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "version": {
          "description": "cluster version",
          "type": "string"
        }
      }
    },
    "Connector_create": {
      "description": "Connector create params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "kind": {
          "description": "connector kind",
          "type": "string"
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "type": {
          "description": "connector type",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Connector_info": {
      "description": "Connector info",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "kind": {
          "description": "connector kind",
          "type": "string"
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "reason": {
          "description": "connector status reason",
          "type": "string"
        },
        "status": {
          "description": "connector status",
          "type": "string"
        },
        "type": {
          "description": "connector type",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Connector_patch": {
      "description": "Connector patch params",
      "type": "object",
      "properties": {
        "annotations": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "required": [
            "default"
          ],
          "additionalProperties": {
            "type": "object"
          }
        },
        "name": {
          "description": "connector name",
          "type": "string"
        },
        "version": {
          "description": "connector version",
          "type": "string"
        }
      }
    },
    "Health_info": {
      "description": "operator info",
      "type": "object",
      "properties": {
        "status": {
          "description": "operator status",
          "type": "string"
        }
      }
    },
    "ListOkErr": {
      "type": "object",
      "properties": {
        "failed": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ListOkErrFailedItems0"
          }
        },
        "successed": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ListOkErrFailedItems0": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        }
      }
    }
  }
}`))
}
