# permissions for end users to view connectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connector-viewer-role
rules:
- apiGroups:
  - vanus.linkall.com
  resources:
  - connectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - connectors/status
  verbs:
  - get
