---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.vanus.ai
  resources:
  - connectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vanus.ai
  resources:
  - connectors/finalizers
  verbs:
  - update
- apiGroups:
  - core.vanus.ai
  resources:
  - connectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.vanus.ai
  resources:
  - vanus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vanus.ai
  resources:
  - vanus/finalizers
  verbs:
  - update
- apiGroups:
  - core.vanus.ai
  resources:
  - vanus/status
  verbs:
  - get
  - patch
  - update
