# permissions for end users to view vanus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vanus-viewer-role
rules:
- apiGroups:
  - core.vanus.ai
  resources:
  - vanus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.vanus.ai
  resources:
  - vanus/status
  verbs:
  - get
