# permissions for end users to edit vanus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vanus-editor-role
rules:
- apiGroups:
  - vanus.vanus.ai
  resources:
  - vanus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.vanus.ai
  resources:
  - vanus/status
  verbs:
  - get
