---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vanus-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - triggers/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - triggers/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - triggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - gateways/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update