---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vanus-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumes
    - persistentvolumeclaims
    - persistentvolumeclaims/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.ai
  resources:
  - cores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.ai
  resources:
  - cores/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.ai
  resources:
  - cores/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.ai
  resources:
  - cores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.ai
  resources:
  - connectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.ai
  resources:
  - connectors/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.ai
  resources:
  - connectors/spec
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.ai
  resources:
  - connectors/status
  verbs:
  - get
  - patch
  - update
