apiVersion: v1
kind: Service
metadata:
  name: vanus-operator
  namespace: vanus
spec:
  selector:
    name: vanus-operator
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30009
      name: proxy