// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/linkall-labs/vanus-operator/api/models"
)

// DeleteConnectorHandlerFunc turns a function with the right signature into a delete connector handler
type DeleteConnectorHandlerFunc func(DeleteConnectorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConnectorHandlerFunc) Handle(params DeleteConnectorParams) middleware.Responder {
	return fn(params)
}

// DeleteConnectorHandler interface for that can handle valid delete connector params
type DeleteConnectorHandler interface {
	Handle(DeleteConnectorParams) middleware.Responder
}

// NewDeleteConnector creates a new http.Handler for the delete connector operation
func NewDeleteConnector(ctx *middleware.Context, handler DeleteConnectorHandler) *DeleteConnector {
	return &DeleteConnector{Context: ctx, Handler: handler}
}

/* DeleteConnector swagger:route DELETE /connector/ connector deleteConnector

delete Connector

*/
type DeleteConnector struct {
	Context *middleware.Context
	Handler DeleteConnectorHandler
}

func (o *DeleteConnector) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConnectorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteConnectorOKBody delete connector o k body
//
// swagger:model DeleteConnectorOKBody
type DeleteConnectorOKBody struct {

	// code
	// Required: true
	Code *int32 `json:"code"`

	// data
	// Required: true
	Data *models.ConnectorInfo `json:"data"`

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete connector o k body
func (o *DeleteConnectorOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteConnectorOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("deleteConnectorOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *DeleteConnectorOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("deleteConnectorOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteConnectorOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *DeleteConnectorOKBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteConnectorOK"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this delete connector o k body based on the context it is used
func (o *DeleteConnectorOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteConnectorOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteConnectorOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteConnectorOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteConnectorOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteConnectorOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
