// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/linkall-labs/vanus-operator/api/models"
)

// NewDeleteConnectorParams creates a new DeleteConnectorParams object
//
// There are no default values defined in the spec.
func NewDeleteConnectorParams() DeleteConnectorParams {

	return DeleteConnectorParams{}
}

// DeleteConnectorParams contains all the bound params for the delete connector operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteConnector
type DeleteConnectorParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*需要删除的 Connector
	  Required: true
	  In: body
	*/
	Connector *models.ConnectorInfo
	/*true 表示强制删除，默认为false
	  In: query
	*/
	Force *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteConnectorParams() beforehand.
func (o *DeleteConnectorParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ConnectorInfo
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("connector", "body", ""))
			} else {
				res = append(res, errors.NewParseError("connector", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Connector = &body
			}
		}
	} else {
		res = append(res, errors.Required("connector", "body", ""))
	}

	qForce, qhkForce, _ := qs.GetOK("force")
	if err := o.bindForce(qForce, qhkForce, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindForce binds and validates parameter Force from query.
func (o *DeleteConnectorParams) bindForce(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Force = &raw

	return nil
}
