// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteConnectorOKCode is the HTTP code returned for type DeleteConnectorOK
const DeleteConnectorOKCode int = 200

/*DeleteConnectorOK OK

swagger:response deleteConnectorOK
*/
type DeleteConnectorOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteConnectorOKBody `json:"body,omitempty"`
}

// NewDeleteConnectorOK creates DeleteConnectorOK with default headers values
func NewDeleteConnectorOK() *DeleteConnectorOK {

	return &DeleteConnectorOK{}
}

// WithPayload adds the payload to the delete connector o k response
func (o *DeleteConnectorOK) WithPayload(payload *DeleteConnectorOKBody) *DeleteConnectorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connector o k response
func (o *DeleteConnectorOK) SetPayload(payload *DeleteConnectorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
