// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/linkall-labs/vanus-operator/api/models"
)

// GetConnectorHandlerFunc turns a function with the right signature into a get connector handler
type GetConnectorHandlerFunc func(GetConnectorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConnectorHandlerFunc) Handle(params GetConnectorParams) middleware.Responder {
	return fn(params)
}

// GetConnectorHandler interface for that can handle valid get connector params
type GetConnectorHandler interface {
	Handle(GetConnectorParams) middleware.Responder
}

// NewGetConnector creates a new http.Handler for the get connector operation
func NewGetConnector(ctx *middleware.Context, handler GetConnectorHandler) *GetConnector {
	return &GetConnector{Context: ctx, Handler: handler}
}

/* GetConnector swagger:route GET /connector/ connector getConnector

get Connector

*/
type GetConnector struct {
	Context *middleware.Context
	Handler GetConnectorHandler
}

func (o *GetConnector) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConnectorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetConnectorOKBody get connector o k body
//
// swagger:model GetConnectorOKBody
type GetConnectorOKBody struct {

	// code
	// Required: true
	Code *int32 `json:"code"`

	// data
	// Required: true
	Data *models.ConnectorInfo `json:"data"`

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this get connector o k body
func (o *GetConnectorOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConnectorOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("getConnectorOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *GetConnectorOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getConnectorOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getConnectorOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *GetConnectorOKBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("getConnectorOK"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get connector o k body based on the context it is used
func (o *GetConnectorOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConnectorOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getConnectorOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetConnectorOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConnectorOKBody) UnmarshalBinary(b []byte) error {
	var res GetConnectorOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
