// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListConnectorOKCode is the HTTP code returned for type ListConnectorOK
const ListConnectorOKCode int = 200

/*ListConnectorOK OK

swagger:response listConnectorOK
*/
type ListConnectorOK struct {

	/*
	  In: Body
	*/
	Payload *ListConnectorOKBody `json:"body,omitempty"`
}

// NewListConnectorOK creates ListConnectorOK with default headers values
func NewListConnectorOK() *ListConnectorOK {

	return &ListConnectorOK{}
}

// WithPayload adds the payload to the list connector o k response
func (o *ListConnectorOK) WithPayload(payload *ListConnectorOKBody) *ListConnectorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list connector o k response
func (o *ListConnectorOK) SetPayload(payload *ListConnectorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConnectorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
