// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchConnectorOKCode is the HTTP code returned for type PatchConnectorOK
const PatchConnectorOKCode int = 200

/*
PatchConnectorOK OK

swagger:response patchConnectorOK
*/
type PatchConnectorOK struct {

	/*
	  In: Body
	*/
	Payload *PatchConnectorOKBody `json:"body,omitempty"`
}

// NewPatchConnectorOK creates PatchConnectorOK with default headers values
func NewPatchConnectorOK() *PatchConnectorOK {

	return &PatchConnectorOK{}
}

// WithPayload adds the payload to the patch connector o k response
func (o *PatchConnectorOK) WithPayload(payload *PatchConnectorOKBody) *PatchConnectorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch connector o k response
func (o *PatchConnectorOK) SetPayload(payload *PatchConnectorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchConnectorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
