// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchConnectorsOKCode is the HTTP code returned for type PatchConnectorsOK
const PatchConnectorsOKCode int = 200

/*
PatchConnectorsOK OK

swagger:response patchConnectorsOK
*/
type PatchConnectorsOK struct {

	/*
	  In: Body
	*/
	Payload *PatchConnectorsOKBody `json:"body,omitempty"`
}

// NewPatchConnectorsOK creates PatchConnectorsOK with default headers values
func NewPatchConnectorsOK() *PatchConnectorsOK {

	return &PatchConnectorsOK{}
}

// WithPayload adds the payload to the patch connectors o k response
func (o *PatchConnectorsOK) WithPayload(payload *PatchConnectorsOKBody) *PatchConnectorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch connectors o k response
func (o *PatchConnectorsOK) SetPayload(payload *PatchConnectorsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchConnectorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
