apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-container-dashboard-api-v2
  namespace: secure-container
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: secure-container-dashboard-api-v2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: secure-container-dashboard-api-v2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - secure-container-dashboard-api-v2
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -addr
        - ":80"
        command:
        - /tmp/server
        image: hub.easystack.io/production/escloud-linux-source-busybox:6.0.2
        imagePullPolicy: IfNotPresent
        name: secure-container-dashboard-api-fake
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
      dnsConfig:
        options:
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - hub.ecns.io
        ip: 10.10.10.10
      nodeSelector:
        kubernetes.io/hostname: node-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - hostPath:
          path: /root/sec
          type: ""
        name: tmpdir
