apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/custom-http-errors: 404,500
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/session-cookie-name: escookie
    kubernetes.io/ingress.class: nginx
  creationTimestamp: "2021-09-18T07:01:28Z"
  generation: 1
  name: ecns-security-dashboard-api-v2
  namespace: secure-container
  resourceVersion: "17532664"
  selfLink: /apis/extensions/v1beta1/namespaces/secure-container/ingresses/ecns-security-dashboard-api
  uid: f3bb4c6d-360f-43e8-84f4-225d3cb6bb64
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: secure-container-dashboard-api-v2
          servicePort: 80
        path: /api/v2/security/
