apiVersion: v1
kind: Service
metadata:
  name: secure-container-dashboard-api-v2
  namespace: secure-container
spec:
  ports:
  - name: ecnsda-pub
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    application: secure-container-dashboard-api-v2
  sessionAffinity: None
  type: ClusterIP
