// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectorCreate Connector create params
//
// swagger:model Connector_create
type ConnectorCreate struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// config
	Config map[string]interface{} `json:"config,omitempty"`

	// connector kind
	Kind string `json:"kind,omitempty"`

	// connector name
	Name string `json:"name,omitempty"`

	// connector service port
	ServicePort string `json:"service_port,omitempty"`

	// connector service type
	ServiceType string `json:"service_type,omitempty"`

	// connector type
	Type string `json:"type,omitempty"`

	// connector version
	Version string `json:"version,omitempty"`
}

// Validate validates this connector create
func (m *ConnectorCreate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connector create based on context it is used
func (m *ConnectorCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectorCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectorCreate) UnmarshalBinary(b []byte) error {
	var res ConnectorCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
