// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectorPatch Connector patch params
//
// swagger:model Connector_patch
type ConnectorPatch struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// config
	Config map[string]interface{} `json:"config,omitempty"`

	// connector name
	Name string `json:"name,omitempty"`

	// connector version
	Version string `json:"version,omitempty"`
}

// Validate validates this connector patch
func (m *ConnectorPatch) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connector patch based on context it is used
func (m *ConnectorPatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectorPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectorPatch) UnmarshalBinary(b []byte) error {
	var res ConnectorPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
