// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TriggerInfo trigger info
//
// swagger:model Trigger_info
type TriggerInfo struct {

	// trigger replicas
	Replicas int32 `json:"replicas,omitempty"`

	// trigger version
	Version string `json:"version,omitempty"`
}

// Validate validates this trigger info
func (m *TriggerInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this trigger info based on context it is used
func (m *TriggerInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TriggerInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TriggerInfo) UnmarshalBinary(b []byte) error {
	var res TriggerInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
