---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vanus-operator
subjects:
- kind: ServiceAccount
  name: vanus-operator
  namespace: vanus
roleRef:
  kind: ClusterRole
  name: vanus-operator
  apiGroup: rbac.authorization.k8s.io
