# Copyright 2023 Linkall Inc.
swagger: "2.0"
consumes:
  - application/json
info:
  description: >
    this document describes the functions, parameters and return values of the vanus operator API
  title: Vanus Operator Interface Document
  version: v0.2.0
produces:
  - application/json
schemes:
  - http
basePath: /api/v1

paths:

  /cluster/:
    get:
      tags:
        - "cluster"
      description: "get Cluster"
      operationId: "getCluster"
      parameters:
        - name: "get"
          in: "body"
          required: true
          schema:
            type: "object"
            $ref: "#/definitions/Cluster_get"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Cluster_info"
              message:
                type: "string"
                default: "success"

    post:
      tags:
        - "cluster"
      description: "create Cluster"
      operationId: "createCluster"
      parameters:
        - name: "create"
          in: "body"
          required: true
          schema:
            type: "object"
            $ref: "#/definitions/Cluster_create"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Cluster_info"
              message:
                type: "string"
                default: "success"

    patch:
      tags:
        - "cluster"
      description: "patch Cluster"
      operationId: "patchCluster"
      parameters:
        - in: body
          name: patch
          description: "patch info"
          schema:
            type: object
            $ref: "#/definitions/Cluster_patch"
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Cluster_info"
              message:
                type: "string"
                default: "success"

    delete:
      tags:
        - "cluster"
      description: "delete Cluster"
      operationId: "deleteCluster"
      parameters:
        - name: "delete"
          in: "body"
          required: true
          schema:
            type: object
            $ref: "#/definitions/Cluster_delete"
          description: "delete Cluster"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Cluster_info"
              message:
                type: "string"
                default: "success"

  /connectors/:
    get:
      tags:
        - "connector"
      operationId: "listConnector"
      description: "list Connector"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: "array"
                items:
                  type: object
                  $ref: "#/definitions/Connector_info"
              message:
                type: "string"
                default: "success"

    post:
      tags:
        - "connector"
      description: "create Connector"
      operationId: "createConnector"
      parameters:
        - name: "connector"
          in: "body"
          required: true
          schema:
            type: "object"
            $ref: "#/definitions/Connector_create"
          description: "Connector info"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Connector_info"
              message:
                type: "string"
                default: "success"

    patch:
      tags:
        - "connector"
      description: "patch Connectors"
      operationId: "patchConnectors"
      parameters:
        - name: "connectors"
          in: "body"
          schema:
            type: "array"
            items:
              type: "object"
              $ref: "#/definitions/Connector_patch"
          required: true
          description: "patch info"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/ListOkErr"
              message:
                type: "string"
                default: "success"

  /connectors/{name}:
    parameters:
      - name: name
        in: path
        type: string
        required: true
        description: "connector name"
    get:
      tags:
        - "connector"
      description: "get Connector"
      operationId: "getConnector"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Connector_info"
              message:
                type: "string"
                default: "success"

    patch:
      tags:
        - "connector"
      description: "patch Connector"
      operationId: "patchConnector"
      parameters:
      parameters:
        - name: "connector"
          in: "body"
          required: true
          schema:
            type: "object"
            $ref: "#/definitions/Connector_patch"
          description: "Connector info"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Connector_info"
              message:
                type: "string"
                default: "success"

    delete:
      tags:
        - "connector"
      description: "delete Connector"
      operationId: "deleteConnector"
      parameters:
        - name: name
          in: path
          type: string
          required: true
          description: "connector name"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Connector_info"
              message:
                type: "string"
                default: "success"

  /healthz/:
    get:
      tags:
        - "healthz"
      description: "healthz"
      operationId: "healthz"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - "code"
              - "data"
              - "message"
            properties:
              code:
                type: "integer"
                format: "int32"
                default: 200
              data:
                type: object
                $ref: "#/definitions/Health_info"
              message:
                type: "string"
                default: "success"

definitions:
  APIResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      data:
        type: "object"
      message:
        type: "string"

  ListOkErr:
    type: "object"
    properties:
      successed:
        type: "array"
        items:
          type: "string"
      failed:
        type: "array"
        items:
          type: "object"
          properties:
            name:
              type: "string"
            reason:
              type: "string"

  Health_info:
    type: "object"
    description: "operator info"
    properties:
      status:
        type: "string"
        description: "operator status"

  Cluster_info:
    type: "object"
    description: "cluster info"
    properties:
      name:
        type: "string"
        description: "cluster name"
      namespace:
        type: "string"
        description: "cluster namespace"
      version:
        type: "string"
        description: "cluster version"
      status:
        type: "string"
        description: "cluster status"

  Cluster_get:
    type: object
    description: "cluster get params"
    properties:
      name:
        type: "string"
        description: "cluster name"
      namespace:
        type: "string"
        description: "cluster namespace"

  Cluster_create:
    type: "object"
    description: "cluster create params"
    properties:
      name:
        type: "string"
        description: "cluster name"
      namespace:
        type: "string"
        description: "cluster namespace"
      version:
        type: "string"
        description: "cluster version"
      annotations:
        type: object
        required:
          - default
        additionalProperties:
          type: string

  Cluster_patch:
    type: object
    description: "cluster patch params"
    properties:
      name:
        type: "string"
        description: "cluster name"
      namespace:
        type: "string"
        description: "cluster namespace"
      version:
        type: "string"
        description: "cluster version"
      annotations:
        type: object
        required:
          - default
        additionalProperties:
          type: string

  Cluster_delete:
    type: object
    description: "cluster create params"
    properties:
      name:
        type: "string"
        description: "cluster name"
      namespace:
        type: "string"
        description: "cluster namespace"
      force:
        type: "boolean"
        default: false
        description: "true means force delete, default false"

  Connector_create:
    type: "object"
    description: "Connector create params"
    properties:
      name:
        type: "string"
        description: "connector name"
      kind:
        type: "string"
        description: "connector kind"
      type:
        type: "string"
        description: "connector type"
      version:
        type: "string"
        description: "connector version"
      config:
        type: object
        required:
          - default
        additionalProperties:
          type: object
      annotations:
        type: object
        required:
          - default
        additionalProperties:
          type: string

  Connector_patch:
    type: "object"
    description: "Connector patch params"
    properties:
      name:
        type: "string"
        description: "connector name"
      version:
        type: "string"
        description: "connector version"
      config:
        type: object
        required:
          - default
        additionalProperties:
          type: object
      annotations:
        type: object
        required:
          - default
        additionalProperties:
          type: string

  Connector_info:
    type: "object"
    description: "Connector info"
    properties:
      name:
        type: "string"
        description: "connector name"
      kind:
        type: "string"
        description: "connector kind"
      type:
        type: "string"
        description: "connector type"
      version:
        type: "string"
        description: "connector version"
      config:
        type: object
        required:
          - default
        additionalProperties:
          type: object
      annotations:
        type: object
        required:
          - default
        additionalProperties:
          type: string
      status:
        type: "string"
        description: "connector status"
      reason:
        type: "string"
        description: "connector status reason"
